#!/bin/bash
ROOT="/*"
ROOT_EXCLUDE_DIRS="--exclude=/media/* --exclude=/tmp/* --exclude=/dev/* --exclu$
DEST_DIR="/home/network/backupDest"

#------------------------------------------------------------------------------$
#             			ADAS BACKUP SCRIPT
#------------------------------------------------------------------------------$
if [ "$USER" != "root" ]; then
    echo "You are not root user, use: sudo backup"
    exit
fi
:PRINTMSG
clear
echo "|-------------------------------------------------------------"
echo "|  BACKUP YOUR SYSTEM: "
OPTIONS="Backup Destination Exit"
LIST="1) Backup 2) Specify Destination 3) Exit"

select opt in $OPTIONS; do
if [ "$opt" = "Exit" ]; then
    clear
    exit

elif [ "$opt" = "Backup" ]; then
    if [ ${#DEST_DIR} -gt 0 ]; then
        ROOT_EXCLUDE_DIRS=${ROOT_EXCLUDE_DIRS///backup*.tgz/$DEST_DIR}
    fi
    tar cvpfz $DEST_DIR/backup.`date +%d%m%y_%k%M`.tgz $ROOT $ROOT_EXCLUDE_DIRS
    echo "| BACKUP COMPLETE!"
    exit
elif [ "$opt" = "Destination" ]; then
    echo "| Actual Destination: $DEST_DIR/backup.`date +%d%m%y_%k%M`.tgz "
    echo "| For change it, just input some ABSOLUTE path "
    echo "| For leave it as it is, just input nothing an push Return"
    read NEW_DEST

    # if the NEW_DEST length is > 0 then we assign it
    if [ ${#NEW_DEST} -gt 0 ]; then
        DEST_DIR="$NEW_DEST"
    fi
    clear

    if [ ! -d $DEST_DIR ]; then
        echo "| WARNING: Specified Destination Dir: $DEST_DIR/ does not exist, $
    fi
    echo "|--------------------------------------------------------------"
    echo "|  BACKUP YOUR SYSTEM: "
    echo $LIST
else
    clear
    echo "| BAD OPTION! Select 1 or 2"
    echo "|--------------------------------------------------------------"
    echo "|  BACKUP YOUR SYSTEM: "
    echo $LIST
fi
done

