#!/bin/bash
ROOT="/*"
ROOT_EXCLUDE_DIRS="--exclude=/bin/z --exclude=/restoreDest --exclude=/backupDest/ --exclude=/home/* --exclude=/backup*.tgz --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found"
DEST_DIR="/backupDest"
LOGFILE="/var/log/backup.log"
DATE=`date +%d%m%y_%k%M`
LOGMESSAGE="Attempted backup at :  "
SBLOG="--> $DATE -- BACKUP -- Full System Back Up -- SUCCESSFULL  Backup <--"
FBLOG="--> $DATE -- BACKUP -- Full System Back Up -- UNSUCCESSFULL  Backup <--"
#------------------------------------------------------------------------------------
#edit             		Adas Backup Script 
#------------------------------------------------------------------------------------
if [ "$USER" != "root" ]; then 
    echo "You're not root, use: sudo backup"
    exit
fi

echo "|  BACKUP YOUR SYSTEM: "
OPTIONS="Backup Destination Exit"
LIST="1) Backup 2) Specify Destination 3) Exit" 

select opt in $OPTIONS; do
if [ "$opt" = "Exit" ]; then
    clear
    exit

elif [ "$opt" = "Backup" ]; then
	if [ ${#DEST_DIR} -gt 0 ]; then
        	ROOT_EXCLUDE_DIRS=${ROOT_EXCLUDE_DIRS/backup*.tgz/$DEST_DIR}
	fi
	tar cvpfz /$DEST_DIR/backup.`date +%d%m%y_%k%M`.tgz $ROOT $ROOT_EXCLUDE_DIRS
	echo "| BACKUP COMPLETE!"
	if  [ "$?" -eq 0 ]
	then
                if [ ! -e /$LOGFILE ]
                then
                        echo $SBLOG > /$LOGFILE
                else
                        echo $SBLOG >> /$LOGFILE
                fi
	else
                if [ ! -e /$LOGFILE ]
                then
                        echo $FBLOG > /$LOGFILE
                else
                        echo $FBLOG >> /$LOGFILE
		fi
	fi

elif [ "$opt" = "Destination" ]; then
    echo "| Place where tar file will be saved: $DEST_DIR/"
    echo "| Current available directories and files"
    cd ~
    ls /
    echo "| To change,input some ABSOLUTE path "
    echo "| To keep it the same press enter"
    read NEW_DEST

    # if the NEW_DEST length is > 0 then we assign it
    if [ ${#NEW_DEST} -gt 0 ]; then
        DEST_DIR="$NEW_DEST"
    fi
    clear

    if [ ! -d $DEST_DIR ]; then
        echo "| WARNING: Specified Destination Dir: $DEST_DIR/ does not exist, yet"
    fi
    echo "|--------------------------------------------------------------"
    echo "|  BACKUP YOUR SYSTEM: "
    echo $LIST-
else
    clear
    echo "| BAD OPTION! Select 1 or 2"
    echo "|--------------------------------------------------------------"
    echo "|  BACKUP YOUR SYSTEM: "
    echo $LIST
fi
done
